MoviesProject/MoviesProject/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movies import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
    path('', movie_views.movies_list, name="home")

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MoviesProject/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

MoviesProject/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.movies_list, name='moviesList'),
    path('createMovie/', views.movies_create, name='createMovie'),
    path('<slug:slug>/createReview/', views.reviews_create, name='createReview'),
    path('<slug:slug>/reviews/delete/<int:review_id>/', views.delete_review, name='delete_review'),
    # path('deleteMovie/', views.delete_movie, name='deleteMovie'),
    path('<slug:slug>/delete/', views.delete_movie, name='delete_movie'),

    path('<slug:slug>/', views.movie_detail, name='detail'),
]

MoviesProject/accounts/models.py
from django.db import models

# Create your models here.

MoviesProject/movies/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Movies(models.Model):
    poster = models.ImageField(default='index.jpg', blank=True)
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    description = models.CharField(max_length=1500)
    Director = models.CharField(max_length=150)
    Four_main_actors = models.CharField(max_length=250)
    year_release = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Reviews(models.Model):
    movie = models.ForeignKey(Movies, default=None, on_delete=models.CASCADE, related_name='reviews')
    year_release_review = models.DateTimeField(auto_now_add=True)
    feedback_stars = models.PositiveIntegerField(default=1, choices=[(i, str(i)) for i in range(1, 6)])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.CharField(max_length=5000)

    def __str__(self):
        return f'{self.user} {self.review} {self.movie} {self.feedback_stars}'

MoviesProject/movies/forms.py
from django import forms
from . import models


class CreateMovie(forms.ModelForm):
    class Meta:
        model = models.Movies
        fields = ['poster', 'title', 'slug', 'description', 'Director', 'Four_main_actors']


class CreateReview(forms.ModelForm):
    class Meta:
        model = models.Reviews
        fields = ['review', 'feedback_stars']
        widgets = {
            'feedback_stars': forms.HiddenInput(),  # Use hidden input for the stars field
        }

MoviesProject/accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect


# Create your views here.


def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('movies:moviesList')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('movies:moviesList')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {"form": form})


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('movies:moviesList')

MoviesProject/movies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
from django.shortcuts import render

# Create your views here.
from .models import Movies, Reviews
from . import forms


def movies_list(request):
    movies = Movies.objects.all().order_by('year_release')
    return render(request, "movies/movies_list.html", {'movies': movies})


def movie_detail(request, slug):
    # movie = Movies.objects.get(slug=slug)
    movie = get_object_or_404(Movies, slug=slug)
    reviews = movie.reviews.all()
    return render(request, 'movies/movie_detail.html', {'movie': movie, 'movies': reviews})


@login_required(login_url="/accounts/login/")
def movies_create(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = forms.CreateMovie(request.POST, request.FILES)
            if form.is_valid():
                # save to the data base
                instance = form.save(commit=False)
                instance.title = form.data.get("title")
                instance.save()
                return redirect('movies:moviesList')
        else:
            form = forms.CreateMovie()
        return render(request, 'movies/create_movie.html', {'form': form})
    else:
        return redirect('movies:moviesList')


@login_required(login_url="/accounts/login/")
def reviews_create(request, slug):
    movie = get_object_or_404(Movies, slug=slug)  # Get the movie using the slug
    if request.method == "POST":
        form = forms.CreateReview(request.POST, request.FILES)
        if form.is_valid():
            # save to the database
            instance = form.save(commit=False)
            instance.movie = movie
            instance.user = request.user
            instance.save()
            return redirect('movies:detail', slug=movie.slug)
    else:
        form = forms.CreateReview()
    return render(request, 'reviews/create_review.html', {'form': form, 'movie': movie})


def reviews_list(request):
    reviews = Reviews.objects.all()
    return render(request, "movies/movie_detail.html", {'movies': reviews})


@login_required(login_url="/accounts/login/")
def delete_review(request, slug, review_id):
    # Get the movie by slug (for redirection purposes)
    movie = get_object_or_404(Movies, slug=slug)

    # Get the review by ID
    review = get_object_or_404(Reviews, id=review_id)

    # Check if the user is the author of the review or an admin
    if request.user == review.user or request.user.is_staff:
        review.delete()
        return redirect('movies:detail', slug=movie.slug)  # Redirect after deletion
    else:
        # Optionally, you could raise a permission denied error or show a message
        return redirect('movies:detail', slug=movie.slug)


@login_required(login_url="/accounts/login/")
def delete_movie(request, slug):
    movie = get_object_or_404(Movies, slug=slug)

    if request.method == "POST":
        movie.delete()
        return redirect('movies:moviesList')

    return redirect('movies:moviesList')

MoviesProject/templates/accounts/login.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}

<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
	    <input type="hidden" name="next" value="{{ request.GET.next }}">
	{% endif %}
    <input type="submit" value="login">
</form>

{% endblock %}

MoviesProject/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}

<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="signup">
</form>

{% endblock %}

MoviesProject/templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movies Blog</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
<body >

    <div class="wrapper" >
        <nav>
	    <ul>
			{% if user.is_authenticated %}
	        <li>
	            <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
	                {% csrf_token %}
	                <button type="submit">Logout</button>
	            </form>
	        </li>
			{% else %}
			<li>
	            <form class="login-link" action="{% url 'accounts:login' %}" method="post">
	                {% csrf_token %}
	                <button type="submit">Login</button>
	            </form>
	        </li>
			<li>
	            <form class="login-link" action="{% url 'accounts:signup' %}" method="post">
	                {% csrf_token %}
	                <button type="submit">Signup</button>
	            </form>
	        </li>
			{% endif %}
			<li>
	            <form class="home-link" action="{% url 'home' %}" method="post">
	                {% csrf_token %}
	                <button type="submit">Home</button>
	            </form>
	        </li>
			{% if user.is_superuser %}
			<li>
	            <form class="addmovie-link" action="{% url 'movies:createMovie' %}" method="post">
	                {% csrf_token %}
	                <button type="submit">Add Movie (Admin)</button>
	            </form>

	        </li>
			{% endif %}

	    </ul>
	</nav>
        {% block content%}
        {% endblock %}
    </div>
<script src="script.js"></script>
</body>
</html>

MoviesProject/templates/movies/create_movie.html
{% extends 'base_layout.html' %}
	{% block content %}
	<div class="create_movie">
	    <h2>create movie</h2>
		<form class="site-form" action="{% url 'movies:createMovie' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form}}
		<input type="submit"  value="createMovie">
		</form>
	</div>
	{% endblock %}

MoviesProject/templates/movies/movie_detail.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}

    <div class="movie-detail">
            <img src="{{ movie.poster.url}}" width="200">
             <h2>{{ movie.title }}</h2>
             <p>{{ movie.description}}</p>
             <p>{{ movie.year_release}}</p>
            <p>{{movie.description}}</p>
            <p>{{movie.Director}}</p>
          <p>{{movie.Four_main_actors}}</p>
    </div>
    <h2>Reviews</h2>
    <input type="submit" value="Add Review" onclick="window.location.href='{% url 'movies:createReview' movie.slug %}'">
<div class="reviews">
    {% for review in movies %}
    <div class="review">
        <p><strong>{{ review.user }}</strong> rated:
            <span class="star-rating-display">
                <!-- Display filled stars -->
                 {% for i in "12345" %}
                    {% if forloop.counter <= review.feedback_stars %}
                        <span class="filled">★</span>
                    {% else %}
                        <span class="empty">☆</span>
                    {% endif %}
                {% endfor %}
            </span>
        </p>
        <p>{{ review.year_release_review }}</p>
        <p>{{ review.review }}</p>
          {% if request.user == review.user or request.user.is_staff %}
            <a href="{% url 'movies:delete_review' movie.slug review.id %}"
               onclick="return confirm('Are you sure you want to delete this review?');"title="Delete Review">
   <i class="fas fa-trash-alt"></i>
            </a>
        {% endif %}
     </div>
    {% endfor %}
</div>

{% endblock %}

MoviesProject/templates/movies/movies_list.html
{% extends 'base_layout.html' %}
{% block content %}
{% load static %}
 <div class="movies-list" >
    {% for movie in movies %}
    <div class="movie">
           <a href="{% url 'movies:detail' slug=movie.slug %}">
        <img src="{{ movie.poster.url}}" width="200">
           </a>
       {% if request.user.is_staff %}
            <form action="{% url 'movies:delete_movie' movie.slug %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('Are you sure you want to delete this movie?');">
                    <i class="fas fa-trash-alt"></i> Delete
                </button>
            </form>
        {% endif %}
    </div>
    {% endfor %}
</div>

{% endblock %}

MoviesProject/templates/reviews/create_review.html
{% extends 'base_layout.html' %}
	{% block content %}
	<div class="create_review">
	    <h2>create review</h2>
		<form class="site-form" action="{% url 'movies:createReview'  movie.slug%}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form}}
    <div class="star-rating-create">
        <input type="radio" name="feedback_stars" value="5" id="5" />
        <label for="5">★</label>
        <input type="radio" name="feedback_stars" value="4" id="4" />
        <label for="4">★</label>
        <input type="radio" name="feedback_stars" value="3" id="3" />
        <label for="3">★</label>
        <input type="radio" name="feedback_stars" value="2" id="2" />
        <label for="2">★</label>
        <input type="radio" name="feedback_stars" value="1" id="1" />
        <label for="1">★</label>




    </div>

		<input type="submit"  value="createReview" onclick="href='{% url 'movies:moviesList' %}'">
		</form>
	</div>
	{% endblock %}